name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          dependencies/arkhelper dir2ark ./_ark ./_build/gen -e -s 4073741823
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: MiloWMV
          path: |
            _build
            